_BASE_: ../Base-AGW.yml

INPUT:
  SIZE_TRAIN: [ 384, 768 ] # 128*6=768
  SIZE_TEST: [ 384, 768 ]

DATASETS:
  NAMES: ("GroupPRCC_SC",)
  TESTS: ("GroupPRCC_SC", "GroupPRCC_CC")

OUTPUT_DIR: logs/GroupPRCC/agw_R50_avghead_all6
