MODEL:
  META_ARCHITECTURE: Baseline

  BACKBONE:
    NAME: build_resnet_backbone
    NORM: BN
    DEPTH: 50x        # 50x
    LAST_STRIDE: 1
    FEAT_DIM: 2048    #2048
    WITH_IBN: False
    PRETRAIN: True

  HEADS:
    NAME: EmbeddingGATHead # EmbeddingGATHead,  EmbeddingHead
    LAYERS: 2
    MULTIHEADS: 4
    NORM: BN 
    WITH_BNNECK: True
    POOL_LAYER: GeneralizedMeanPoolingP # GeneralizedMeanPoolingP # GlobalAvgPool
    NECK_FEAT: before # before 
    CLS_LAYER: Linear

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1. # 1.

INPUT:
  SIZE_TRAIN: [ 256, 768 ] # 128*6=768
  SIZE_TEST: [ 256, 768 ]

  REA:
    ENABLED: True
    PROB: 0.5

  FLIP:
    ENABLED: True

  PADDING:
    ENABLED: True

DATALOADER:
  SAMPLER_TRAIN: NaiveIdentitySampler
  NUM_INSTANCE: 32 # 16 for standard , 4
  NUM_WORKERS: 8

SOLVER:
  AMP:
    ENABLED: True
  OPT: Adam
  MAX_EPOCH: 120 # 60 for all, 120 for us
  BASE_LR: 0.00035
  HEADS_LR_FACTOR: 0.1 # 1.0 for baseline, 0.1 for us
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
  IMS_PER_BATCH:  64 # 128

  SCHED: MultiStepLR
  STEPS: [ 40, 90 ] # [ 40, 50 ] for 60 epoch, [ 40, 90 ] for 120 epoch
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128
  RERANK:
    ENABLED: False

CUDNN_BENCHMARK: True
